# Generated by Django 3.2.6 on 2021-08-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Content', models.TextField(max_length=100)),
                ('postdate', models.DateField(auto_now_add=True, null=True)),
                ('Category', models.CharField(choices=[('Local,', '現地'), ('Japan', '日本'), ('France', 'フランス'), ('Germany', 'ドイツ'), ('Korea', '韓国'), ('Spain', 'スペイン')], default='Local', max_length=50, null=True)),
            ],
        ),
    ]
