# Generated by Django 3.2.6 on 2021-08-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='Category',
        ),
        migrations.AddField(
            model_name='schools',
            name='category',
            field=models.CharField(choices=[('Local', '現地'), ('Japan', '日本'), ('France', 'フランス'), ('Germany', 'ドイツ'), ('Korea', '韓国'), ('Spain', 'スペイン')], default='Local', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='price',
            field=models.CharField(default='70 per hour', max_length=100),
        ),
    ]
