# Generated by Django 3.2.6 on 2021-08-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20210826_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='category',
            new_name='Category',
        ),
    ]
