# Generated by Django 3.2.6 on 2021-08-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_rename_category_schools_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='Name',
            new_name='name',
        ),
    ]
